/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Copy: typeof import('./src/components/copy/index.vue')['default']
    Cropper: typeof import('./src/components/cropper/index.vue')['default']
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    Modal: typeof import('./src/components/modal/index.vue')['default']
    MyTable: typeof import('./src/components/MyTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TableVirtually: typeof import('./src/components/TableVirtually.vue')['default']
    VirtualScroller: typeof import('./src/components/virtual-scroller/index.vue')['default']
    XlDraggable: typeof import('./src/components/XlDraggable.vue')['default']
    XlUpload: typeof import('./src/components/xl-upload/index.vue')['default']
  }
}
